<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\SerialLog.Core\SerialLog.Core.csproj" />
    <ProjectReference Include="..\SerialLog.Update\SerialLog.Update.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <SelfContained>true</SelfContained>
    <Version>0.2.12</Version>
    <AssemblyVersion>0.2.12.0</AssemblyVersion>
    <FileVersion>0.2.12.0</FileVersion>
    <InformationalVersion>0.2.12</InformationalVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>Assets\AppIcon.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Assets\AppIcon.ico" />
    <None Remove="Assets\BrandLogo.png" />
    <Resource Include="Assets\AppIcon.ico" />
    <Resource Include="Assets\BrandLogo.png" />
  </ItemGroup>

</Project>
